# https://help.github.com/en/articles/metadata-syntax-for-github-actions

author: 'Venditan'

branding:
    icon: 'check'
    color: 'blue'

description: 'Use PHP-CS-Fixer via GithubAction.'

name: 'PHP-CS-Fixer'

runs:
    using: 'docker'
    image: 'Dockerfile'
    env:
        FILES: ${{ steps.file_changes.outputs.files}}
